-- Male Designs
INSERT INTO clothing_designs (image_url, prompt, style, gender) VALUES
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0001.jpg', 'Clothing Design#M1', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0002.jpg', 'Clothing Design#M2', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0003.jpg', 'Clothing Design#M3', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0004.jpg', 'Clothing Design#M4', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0005.jpg', 'Clothing Design#M5', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0006.jpg', 'Clothing Design#M6', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0007.jpg', 'Clothing Design#M7', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0008.jpg', 'Clothing Design#M8', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0009.jpg', 'Clothing Design#M9', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0010.jpg', 'Clothing Design#M10', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0011.jpg', 'Clothing Design#M11', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0012.jpg', 'Clothing Design#M12', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0013.jpg', 'Clothing Design#M13', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0014.jpg', 'Clothing Design#M14', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0015.jpg', 'Clothing Design#M15', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0016.jpg', 'Clothing Design#M16', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0017.jpg', 'Clothing Design#M17', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0018.jpg', 'Clothing Design#M18', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0019.jpg', 'Clothing Design#M19', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0020.jpg', 'Clothing Design#M20', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0021.jpg', 'Clothing Design#M21', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0022.jpg', 'Clothing Design#M22', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0023.jpg', 'Clothing Design#M23', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0024.jpg', 'Clothing Design#M24', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0025.jpg', 'Clothing Design#M25', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0026.jpg', 'Clothing Design#M26', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0027.jpg', 'Clothing Design#M27', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0028.jpg', 'Clothing Design#M28', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0029.jpg', 'Clothing Design#M29', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0030.jpg', 'Clothing Design#M30', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0031.jpg', 'Clothing Design#M31', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0032.jpg', 'Clothing Design#M32', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0033.jpg', 'Clothing Design#M33', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0034.jpg', 'Clothing Design#M34', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0035.jpg', 'Clothing Design#M35', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0036.jpg', 'Clothing Design#M36', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0037.jpg', 'Clothing Design#M37', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0038.jpg', 'Clothing Design#M38', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0039.jpg', 'Clothing Design#M39', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0040.jpg', 'Clothing Design#M40', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0041.jpg', 'Clothing Design#M41', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0042.jpg', 'Clothing Design#M42', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0043.jpg', 'Clothing Design#M43', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0044.jpg', 'Clothing Design#M44', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0045.jpg', 'Clothing Design#M45', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0046.jpg', 'Clothing Design#M46', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0047.jpg', 'Clothing Design#M47', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0048.jpg', 'Clothing Design#M48', 'Formal', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0049.jpg', 'Clothing Design#M49', 'Casual', 'Male'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/design_0050.jpg', 'Clothing Design#M50', 'Formal', 'Male');

-- Female Designs
INSERT INTO clothing_designs (image_url, prompt, style, gender) VALUES
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0001.jpg', 'Clothing Design#F1', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0002.jpg', 'Clothing Design#F2', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0003.jpg', 'Clothing Design#F3', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0004.jpg', 'Clothing Design#F4', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0005.jpg', 'Clothing Design#F5', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0006.jpg', 'Clothing Design#F6', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0007.jpg', 'Clothing Design#F7', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0008.jpg', 'Clothing Design#F8', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0009.jpg', 'Clothing Design#F9', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0010.jpg', 'Clothing Design#F10', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0011.jpg', 'Clothing Design#F11', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0012.jpg', 'Clothing Design#F12', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0013.jpg', 'Clothing Design#F13', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0014.jpg', 'Clothing Design#F14', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0015.jpg', 'Clothing Design#F15', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0016.jpg', 'Clothing Design#F16', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0017.jpg', 'Clothing Design#F17', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0018.jpg', 'Clothing Design#F18', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0019.jpg', 'Clothing Design#F19', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0020.jpg', 'Clothing Design#F20', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0021.jpg', 'Clothing Design#F21', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0022.jpg', 'Clothing Design#F22', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0023.jpg', 'Clothing Design#F23', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0024.jpg', 'Clothing Design#F24', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0025.jpg', 'Clothing Design#F25', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0026.jpg', 'Clothing Design#F26', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0027.jpg', 'Clothing Design#F27', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0028.jpg', 'Clothing Design#F28', 'Formal', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0029.jpg', 'Clothing Design#F29', 'Casual', 'Female'),
('https://ik.imagekit.io/sp7ub8zm6/fashion_designs/female_0030.jpg', 'Clothing Design#F30', 'Formal', 'Female');



INSERT INTO users (username, email, password) VALUES
('admin', 'adminuser@gmail.com', 'password'),
('testuser1', 'testuser1@example.com', 'password1'),
('testuser2', 'testuser2@example.com', 'password2'),
('testuser3', 'testuser3@example.com', 'password3'),
('designer_male', 'designer_male@example.com', 'designer123'),
('designer_female', 'designer_female@example.com', 'designer123'),
('viewer01', 'viewer01@example.com', 'viewerpass'),
('viewer02', 'viewer02@example.com', 'viewerpass'),
('fashion_tester', 'tester@fashionlab.com', 'test1234'),
('mock_user01', 'mock01@test.com', 'mockpass'),
('mock_user02', 'mock02@test.com', 'mockpass');

-- Sample Reviews
INSERT INTO review (name, rating, comment, likes, created_at) VALUES
('Alice', 5, 'Amazing platform! The virtual try-on feature is a game changer.', 3, CURRENT_TIMESTAMP),
('Bob', 4, 'Great designs and easy to use. Would love more outfit suggestions.', 2, CURRENT_TIMESTAMP),
('Priya', 5, 'Loved the personalized recommendations. Highly recommended!', 5, CURRENT_TIMESTAMP),
('John', 3, 'Good experience overall, but the camera try-on could be faster.', 1, CURRENT_TIMESTAMP),
('Sara', 4, 'The marketplace is very useful for comparing styles.', 0, CURRENT_TIMESTAMP);